# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcaddr',
            name='oldAddr',
            field=models.CharField(default='111', max_length=34),
        ),
    ]
