# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_btcaddr_oldaddr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcaddr',
            name='oldAddr',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
