# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20170413_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='btcaddr',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
