# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missed',
            name='trans_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_id',
            field=models.CharField(max_length=100),
        ),
    ]
