# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 01:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_auto_20170414_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missed',
            name='was_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='was_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
