# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_auto_20170506_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcaddr',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
