# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_auto_20170507_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcaddr',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code'),
        ),
    ]
