# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0015_auto_20170508_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momo_number', models.CharField(max_length=12)),
                ('momo_name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='momo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='btcaddr',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='trans_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='image_proof',
            field=models.ImageField(blank=True, null=True, upload_to='proofs'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='text_proof',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='btcAddr',
        ),
    ]
