# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0016_auto_20180117_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_against', to=settings.AUTH_USER_MODEL)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_by', to=settings.AUTH_USER_MODEL)),
                ('trans_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='financial.Transaction')),
            ],
        ),
    ]
