# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='trans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='financial.Transaction'),
        ),
    ]
