# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_auto_20180117_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='momodata',
            name='changeCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='trans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='financial.Transaction'),
        ),
    ]
