# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_auto_20180117_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='trans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='financial.Transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
