# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='additional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
