# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0003_notif_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notif_count',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
