# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=10)),
                ('doner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downliner', to=settings.AUTH_USER_MODEL)),
                ('p1', models.ForeignKey(default='cyberick', on_delete=django.db.models.deletion.CASCADE, related_name='parent1', to=settings.AUTH_USER_MODEL)),
                ('p2', models.ForeignKey(default='cyberick', on_delete=django.db.models.deletion.CASCADE, related_name='parent2', to=settings.AUTH_USER_MODEL)),
                ('p3', models.ForeignKey(default='cyberick', on_delete=django.db.models.deletion.CASCADE, related_name='parent3', to=settings.AUTH_USER_MODEL)),
                ('p4', models.ForeignKey(default='cyberick', on_delete=django.db.models.deletion.CASCADE, related_name='parent4', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
