# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='p1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tree',
            name='p2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tree',
            name='p3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tree',
            name='p4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent4', to=settings.AUTH_USER_MODEL),
        ),
    ]
