# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geneology', '0004_auto_20170511_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descendant',
            old_name='last_login',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='last_login',
            new_name='timestamp',
        ),
    ]
