# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 21:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sponsor_name', models.CharField(default='admin', max_length=200)),
                ('securityQ', models.CharField(max_length=200)),
                ('securityA', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('phoneNum', models.CharField(max_length=200)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_soc', models.BooleanField(default=True)),
                ('autosave', models.BooleanField(default=False)),
                ('allowemail', models.BooleanField(default=True)),
                ('show_pp', models.BooleanField(default=True)),
                ('show_num', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='option', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.FileField(default='/user/default.jpg', upload_to='user/')),
                ('fb_link', models.CharField(blank=True, max_length=200, null=True)),
                ('twi_link', models.CharField(blank=True, max_length=200, null=True)),
                ('lin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('gm_link', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
