# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='sponsor',
        ),
    ]
