# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_remove_dashboard_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
