# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_dashboard_sponsor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='ref_id',
            field=models.CharField(default=b'1ae8f991ce', max_length=10),
        ),
    ]
