# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20170401_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='level',
        ),
    ]
