# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_dashboard_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
