# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20170405_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='expire',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
