# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 07:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_dashboard_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
