# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20170414_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
