# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-14 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20170414_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
