# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-15 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_dashboard_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='dsd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='option',
            name='dsi',
            field=models.BooleanField(default=False),
        ),
    ]
