# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_dashboard_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='reset_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
