# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_dashboard_reset_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='automaticRate',
            field=models.BooleanField(default=True),
        ),
    ]
